packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@nestjs/core': false
  electron: true
  electron-winstaller: true
  esbuild: true

onlyBuiltDependencies:
  - electron
  - esbuild

ignoredBuiltDependencies:
  - '@nestjs/core'
